// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Animal
{
    public int Id { get; set; }

    public int? AnimalTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Age { get; set; }

    public string Gender { get; set; }

    public string Weight { get; set; }

    public int? Quantity { get; set; }

    public DateOnly? ArrivalDate { get; set; }

    public string Notes { get; set; }

    public string Status { get; set; }

    public string UrlImage { get; set; }

    public virtual ICollection<AnimalCage> AnimalCages { get; set; } = new List<AnimalCage>();

    public virtual ICollection<AnimalIncidentHistory> AnimalIncidentHistories { get; set; } = new List<AnimalIncidentHistory>();

    public virtual AnimalType AnimalType { get; set; }

    public virtual ICollection<AnimalUpdateHistory> AnimalUpdateHistories { get; set; } = new List<AnimalUpdateHistory>();
}