// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Category
{
    public int Id { get; set; }

    public int? Name { get; set; }

    public virtual ICollection<Status> Statuses { get; set; } = new List<Status>();
}