// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class IncompatibleAnimalType
{
    public int Id { get; set; }

    public int? AnimalTypeId1 { get; set; }

    public int? AnimalTypeId2 { get; set; }

    public string Reason { get; set; }

    public int? StatusId { get; set; }

    public virtual AnimalType AnimalTypeId1Navigation { get; set; }

    public virtual AnimalType AnimalTypeId2Navigation { get; set; }

    public virtual Status Status { get; set; }
}