// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Individual
{
    public int Id { get; set; }

    public int? AnimalId { get; set; }

    public DateOnly? BirthDate { get; set; }

    public string Name { get; set; }

    public string Age { get; set; }

    public string Gender { get; set; }

    public string Weight { get; set; }

    public string Height { get; set; }

    public DateOnly? ArrivalDate { get; set; }

    public string Notes { get; set; }

    public string Status { get; set; }

    public virtual Animal Animal { get; set; }
}