// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class News
{
    public int Id { get; set; }

    public int? AccountId { get; set; }

    public string Headline { get; set; }

    public string Content { get; set; }

    public DateTime? Date { get; set; }

    public int? StatusId { get; set; }

    public virtual Account Account { get; set; }

    public virtual Status Status { get; set; }
}