// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Report
{
    public int Id { get; set; }

    public int? SenderId { get; set; }

    public int? ReceiverId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public DateTime? Date { get; set; }

    public int? StatusId { get; set; }

    public virtual Account Receiver { get; set; }

    public virtual ICollection<ReportAttachment> ReportAttachments { get; set; } = new List<ReportAttachment>();

    public virtual Account Sender { get; set; }

    public virtual Status Status { get; set; }
}