// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Schedule
{
    public int Id { get; set; }

    public int? AccountId { get; set; }

    public DateOnly? Date { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}