// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class TaskEstimate
{
    public int Id { get; set; }

    public int? TaskTypeId { get; set; }

    public int? AnimalTypeId { get; set; }

    public string TimeEstimate { get; set; }

    public string ImplementationProcess { get; set; }

    public int? StatusId { get; set; }

    public virtual AnimalType AnimalType { get; set; }

    public virtual Status Status { get; set; }

    public virtual TaskType TaskType { get; set; }
}