// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Team
{
    public int Id { get; set; }

    public int? ZooAreaId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? StatusId { get; set; }

    public virtual ICollection<LeaderAssign> LeaderAssigns { get; set; } = new List<LeaderAssign>();

    public virtual ICollection<MemberAssign> MemberAssigns { get; set; } = new List<MemberAssign>();

    public virtual Status Status { get; set; }

    public virtual ZooArea ZooArea { get; set; }
}