// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace BO.Models;

public partial class Zoo_Management_And_Staff_Operations_SystemContext : DbContext
{
    public Zoo_Management_And_Staff_Operations_SystemContext()
    {
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(GetConnectionString());
            }
        }
    }
    private string GetConnectionString()
    {
        IConfiguration config = new ConfigurationBuilder()
             .SetBasePath(Path.Combine(Directory.GetCurrentDirectory(), "..", "Zoo_Management_And_Staff_Operations_System"))
             .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
             .Build();
        var strConn = config["ConnectionStrings:DefaultConnection"];

        return strConn;
    }
    public Zoo_Management_And_Staff_Operations_SystemContext(DbContextOptions<Zoo_Management_And_Staff_Operations_SystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AbsentTime> AbsentTimes { get; set; }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Animal> Animals { get; set; }

    public virtual DbSet<AnimalAssign> AnimalAssigns { get; set; }

    public virtual DbSet<AnimalCage> AnimalCages { get; set; }

    public virtual DbSet<AnimalImage> AnimalImages { get; set; }

    public virtual DbSet<AnimalIncidentHistory> AnimalIncidentHistories { get; set; }

    public virtual DbSet<AnimalType> AnimalTypes { get; set; }

    public virtual DbSet<AnimalUpdateHistory> AnimalUpdateHistories { get; set; }

    public virtual DbSet<Application> Applications { get; set; }

    public virtual DbSet<ApplicationType> ApplicationTypes { get; set; }

    public virtual DbSet<Cage> Cages { get; set; }

    public virtual DbSet<CageUpdateHistory> CageUpdateHistories { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Evaluation> Evaluations { get; set; }

    public virtual DbSet<Flock> Flocks { get; set; }

    public virtual DbSet<IncompatibleAnimalType> IncompatibleAnimalTypes { get; set; }

    public virtual DbSet<Individual> Individuals { get; set; }

    public virtual DbSet<LeaderAssign> LeaderAssigns { get; set; }

    public virtual DbSet<MemberAssign> MemberAssigns { get; set; }

    public virtual DbSet<News> News { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<ReportAttachment> ReportAttachments { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<StatusCategory> StatusCategories { get; set; }

    public virtual DbSet<Task> Tasks { get; set; }

    public virtual DbSet<TaskEstimate> TaskEstimates { get; set; }

    public virtual DbSet<TaskType> TaskTypes { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<ZooArea> ZooAreas { get; set; }

    public virtual DbSet<ZooAreaImage> ZooAreaImages { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AbsentTime>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AbsentTi__3213E83F182D86D0");

            entity.ToTable("AbsentTime");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccountId).HasColumnName("account_id");
            entity.Property(e => e.FromDate).HasColumnName("from_date");
            entity.Property(e => e.Reason).HasColumnName("reason");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.ToDate).HasColumnName("to_date");

            entity.HasOne(d => d.Account).WithMany(p => p.AbsentTimes)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__AbsentTim__accou__0A9D95DB");

            entity.HasOne(d => d.Status).WithMany(p => p.AbsentTimes)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__AbsentTim__statu__0B91BA14");
        });

        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Account__3213E83FDED5B81F");

            entity.ToTable("Account");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccountName)
                .HasMaxLength(500)
                .HasColumnName("account_name");
            entity.Property(e => e.CreatedDate).HasColumnName("created_date");
            entity.Property(e => e.Password)
                .HasMaxLength(500)
                .HasColumnName("password");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.UpdatedDate).HasColumnName("updated_date");

            entity.HasOne(d => d.Role).WithMany(p => p.Accounts)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__Account__role_id__0C85DE4D");

            entity.HasOne(d => d.Status).WithMany(p => p.Accounts)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Account__status___0D7A0286");
        });

        modelBuilder.Entity<Animal>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Animal__3213E83F6261EFF5");

            entity.ToTable("Animal");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnimalTypeId).HasColumnName("animal_type_id");
            entity.Property(e => e.Classify)
                .HasMaxLength(500)
                .HasColumnName("classify");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.StatusId).HasColumnName("status_id");

            entity.HasOne(d => d.AnimalType).WithMany(p => p.Animals)
                .HasForeignKey(d => d.AnimalTypeId)
                .HasConstraintName("FK__Animal__animal_t__0E6E26BF");

            entity.HasOne(d => d.Status).WithMany(p => p.Animals)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Animal__status_i__0F624AF8");
        });

        modelBuilder.Entity<AnimalAssign>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AnimalAs__3213E83FBD7B181F");

            entity.ToTable("AnimalAssign");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnimalCageId).HasColumnName("animal_cage_id");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.TaskId).HasColumnName("task_id");

            entity.HasOne(d => d.AnimalCage).WithMany(p => p.AnimalAssigns)
                .HasForeignKey(d => d.AnimalCageId)
                .HasConstraintName("FK__AnimalAss__anima__10566F31");

            entity.HasOne(d => d.Status).WithMany(p => p.AnimalAssigns)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__AnimalAss__statu__114A936A");

            entity.HasOne(d => d.Task).WithMany(p => p.AnimalAssigns)
                .HasForeignKey(d => d.TaskId)
                .HasConstraintName("FK__AnimalAss__task___123EB7A3");
        });

        modelBuilder.Entity<AnimalCage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AnimalCa__3213E83FD6B927AF");

            entity.ToTable("AnimalCage");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnimalId).HasColumnName("animal_id");
            entity.Property(e => e.CageId).HasColumnName("cage_id");
            entity.Property(e => e.FromDate).HasColumnName("from_date");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.ToDate).HasColumnName("to_date");

            entity.HasOne(d => d.Animal).WithMany(p => p.AnimalCages)
                .HasForeignKey(d => d.AnimalId)
                .HasConstraintName("FK__AnimalCag__anima__1332DBDC");

            entity.HasOne(d => d.Cage).WithMany(p => p.AnimalCages)
                .HasForeignKey(d => d.CageId)
                .HasConstraintName("FK__AnimalCag__cage___14270015");

            entity.HasOne(d => d.Status).WithMany(p => p.AnimalCages)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__AnimalCag__statu__151B244E");
        });

        modelBuilder.Entity<AnimalImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AnimalIm__3213E83FA70AAAF4");

            entity.ToTable("AnimalImage");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnimalId).HasColumnName("animal_id");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.UrlImage).HasColumnName("url_image");

            entity.HasOne(d => d.Animal).WithMany(p => p.AnimalImages)
                .HasForeignKey(d => d.AnimalId)
                .HasConstraintName("FK__AnimalIma__anima__160F4887");
        });

        modelBuilder.Entity<AnimalIncidentHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AnimalIn__3213E83F14F3581E");

            entity.ToTable("AnimalIncidentHistory");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnimalId).HasColumnName("animal_id");
            entity.Property(e => e.Content)
                .HasMaxLength(500)
                .HasColumnName("content");
            entity.Property(e => e.FromDate).HasColumnName("from_date");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.ToDate).HasColumnName("to_date");

            entity.HasOne(d => d.Animal).WithMany(p => p.AnimalIncidentHistories)
                .HasForeignKey(d => d.AnimalId)
                .HasConstraintName("FK__AnimalInc__anima__17036CC0");

            entity.HasOne(d => d.Status).WithMany(p => p.AnimalIncidentHistories)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__AnimalInc__statu__17F790F9");
        });

        modelBuilder.Entity<AnimalType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AnimalTy__3213E83F512E365D");

            entity.ToTable("AnimalType");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Characteristics)
                .HasMaxLength(500)
                .HasColumnName("characteristics");
            entity.Property(e => e.ConservationStatus)
                .HasMaxLength(20)
                .HasColumnName("conservation_status");
            entity.Property(e => e.Diet)
                .HasMaxLength(500)
                .HasColumnName("diet");
            entity.Property(e => e.Distribution)
                .HasMaxLength(500)
                .HasColumnName("distribution");
            entity.Property(e => e.EatFrequency)
                .HasMaxLength(500)
                .HasColumnName("eat_frequency");
            entity.Property(e => e.EnglishName)
                .HasMaxLength(500)
                .HasColumnName("english_name");
            entity.Property(e => e.Family)
                .HasMaxLength(500)
                .HasColumnName("family");
            entity.Property(e => e.Habitat)
                .HasMaxLength(500)
                .HasColumnName("habitat");
            entity.Property(e => e.Reproduction)
                .HasMaxLength(500)
                .HasColumnName("reproduction");
            entity.Property(e => e.ScientificName)
                .HasMaxLength(500)
                .HasColumnName("scientific_name");
            entity.Property(e => e.UrlImage).HasColumnName("url_image");
            entity.Property(e => e.VietnameseName)
                .HasMaxLength(500)
                .HasColumnName("vietnamese_name");
            entity.Property(e => e.WeightRange)
                .HasMaxLength(500)
                .HasColumnName("weight_range");
        });

        modelBuilder.Entity<AnimalUpdateHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AnimalUp__3213E83FA46C2CB5");

            entity.ToTable("AnimalUpdateHistory");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccountId).HasColumnName("account_id");
            entity.Property(e => e.AnimalId).HasColumnName("animal_id");
            entity.Property(e => e.Detail)
                .HasMaxLength(500)
                .HasColumnName("detail");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.UpdateDate).HasColumnName("update_date");

            entity.HasOne(d => d.Account).WithMany(p => p.AnimalUpdateHistories)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__AnimalUpd__accou__18EBB532");

            entity.HasOne(d => d.Animal).WithMany(p => p.AnimalUpdateHistories)
                .HasForeignKey(d => d.AnimalId)
                .HasConstraintName("FK__AnimalUpd__anima__19DFD96B");
        });

        modelBuilder.Entity<Application>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Applicat__3213E83FC3F92284");

            entity.ToTable("Application");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ApplicationTypeId).HasColumnName("application_type_id");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.Details)
                .HasMaxLength(500)
                .HasColumnName("details");
            entity.Property(e => e.RecieverId).HasColumnName("reciever_id");
            entity.Property(e => e.Reply)
                .HasMaxLength(500)
                .HasColumnName("reply");
            entity.Property(e => e.SenderId).HasColumnName("sender_id");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.Title)
                .HasMaxLength(500)
                .HasColumnName("title");

            entity.HasOne(d => d.ApplicationType).WithMany(p => p.Applications)
                .HasForeignKey(d => d.ApplicationTypeId)
                .HasConstraintName("FK__Applicati__appli__1AD3FDA4");

            entity.HasOne(d => d.Reciever).WithMany(p => p.ApplicationRecievers)
                .HasForeignKey(d => d.RecieverId)
                .HasConstraintName("FK__Applicati__recie__1BC821DD");

            entity.HasOne(d => d.Sender).WithMany(p => p.ApplicationSenders)
                .HasForeignKey(d => d.SenderId)
                .HasConstraintName("FK__Applicati__sende__1CBC4616");

            entity.HasOne(d => d.Status).WithMany(p => p.Applications)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Applicati__statu__1DB06A4F");
        });

        modelBuilder.Entity<ApplicationType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Applicat__3213E83FFDE8EAE7");

            entity.ToTable("ApplicationType");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .HasMaxLength(500)
                .HasColumnName("name");
            entity.Property(e => e.StatusId).HasColumnName("status_id");

            entity.HasOne(d => d.Status).WithMany(p => p.ApplicationTypes)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Applicati__statu__1EA48E88");
        });

        modelBuilder.Entity<Cage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Cage__3213E83F946BB76F");

            entity.ToTable("Cage");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Classify)
                .HasMaxLength(500)
                .HasColumnName("classify");
            entity.Property(e => e.CurrentQuantity).HasColumnName("current_quantity");
            entity.Property(e => e.DateCreate).HasColumnName("date_create");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.MaxQuantity).HasColumnName("max_quantity");
            entity.Property(e => e.Name)
                .HasMaxLength(500)
                .HasColumnName("name");
            entity.Property(e => e.Size)
                .HasMaxLength(500)
                .HasColumnName("size");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.UrlImage).HasColumnName("url_image");
            entity.Property(e => e.ZooAreaId).HasColumnName("zoo_area_id");

            entity.HasOne(d => d.Status).WithMany(p => p.Cages)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Cage__status_id__1F98B2C1");

            entity.HasOne(d => d.ZooArea).WithMany(p => p.Cages)
                .HasForeignKey(d => d.ZooAreaId)
                .HasConstraintName("FK__Cage__zoo_area_i__208CD6FA");
        });

        modelBuilder.Entity<CageUpdateHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CageUpda__3213E83FE34B379D");

            entity.ToTable("CageUpdateHistory");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccountId).HasColumnName("account_id");
            entity.Property(e => e.CageId).HasColumnName("cage_id");
            entity.Property(e => e.Detail)
                .HasMaxLength(500)
                .HasColumnName("detail");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.UpdateDate).HasColumnName("update_date");

            entity.HasOne(d => d.Account).WithMany(p => p.CageUpdateHistories)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__CageUpdat__accou__2180FB33");

            entity.HasOne(d => d.Cage).WithMany(p => p.CageUpdateHistories)
                .HasForeignKey(d => d.CageId)
                .HasConstraintName("FK__CageUpdat__cage___22751F6C");

            entity.HasOne(d => d.Status).WithMany(p => p.CageUpdateHistories)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__CageUpdat__statu__236943A5");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Category__3213E83FDBD3CEBB");

            entity.ToTable("Category");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .HasMaxLength(500)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Evaluation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Evaluati__3213E83F0850EC80");

            entity.ToTable("Evaluation");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.Details)
                .HasMaxLength(500)
                .HasColumnName("details");
            entity.Property(e => e.LeaderId).HasColumnName("leader_id");
            entity.Property(e => e.MaxScore).HasColumnName("max_score");
            entity.Property(e => e.MemberId).HasColumnName("member_id");
            entity.Property(e => e.Score).HasColumnName("score");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.Title)
                .HasMaxLength(500)
                .HasColumnName("title");

            entity.HasOne(d => d.Leader).WithMany(p => p.Evaluations)
                .HasForeignKey(d => d.LeaderId)
                .HasConstraintName("FK__Evaluatio__leade__245D67DE");

            entity.HasOne(d => d.Member).WithMany(p => p.Evaluations)
                .HasForeignKey(d => d.MemberId)
                .HasConstraintName("FK__Evaluatio__membe__25518C17");

            entity.HasOne(d => d.Status).WithMany(p => p.Evaluations)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Evaluatio__statu__2645B050");
        });

        modelBuilder.Entity<Flock>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Flock__3213E83FFAEB4E8D");

            entity.ToTable("Flock");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnimalId).HasColumnName("animal_id");
            entity.Property(e => e.Notes)
                .HasMaxLength(500)
                .HasColumnName("notes");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.StatusId).HasColumnName("status_id");

            entity.HasOne(d => d.Animal).WithMany(p => p.Flocks)
                .HasForeignKey(d => d.AnimalId)
                .HasConstraintName("FK__Flock__animal_id__2739D489");

            entity.HasOne(d => d.Status).WithMany(p => p.Flocks)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Flock__status_id__282DF8C2");
        });

        modelBuilder.Entity<IncompatibleAnimalType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Incompat__3213E83FC1D67F93");

            entity.ToTable("IncompatibleAnimalType");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnimalTypeId1).HasColumnName("animal_type_id_1");
            entity.Property(e => e.AnimalTypeId2).HasColumnName("animal_type_id_2");
            entity.Property(e => e.Reason)
                .HasMaxLength(500)
                .HasColumnName("reason");
            entity.Property(e => e.StatusId).HasColumnName("status_id");

            entity.HasOne(d => d.AnimalTypeId1Navigation).WithMany(p => p.IncompatibleAnimalTypeAnimalTypeId1Navigations)
                .HasForeignKey(d => d.AnimalTypeId1)
                .HasConstraintName("FK__Incompati__anima__29221CFB");

            entity.HasOne(d => d.AnimalTypeId2Navigation).WithMany(p => p.IncompatibleAnimalTypeAnimalTypeId2Navigations)
                .HasForeignKey(d => d.AnimalTypeId2)
                .HasConstraintName("FK__Incompati__anima__2A164134");

            entity.HasOne(d => d.Status).WithMany(p => p.IncompatibleAnimalTypes)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Incompati__statu__2B0A656D");
        });

        modelBuilder.Entity<Individual>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Individu__3213E83F996FB298");

            entity.ToTable("Individual");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Age)
                .HasMaxLength(500)
                .HasColumnName("age");
            entity.Property(e => e.AnimalId).HasColumnName("animal_id");
            entity.Property(e => e.ArrivalDate).HasColumnName("arrival_date");
            entity.Property(e => e.BirthDate).HasColumnName("birth_date");
            entity.Property(e => e.Gender)
                .HasMaxLength(500)
                .HasColumnName("gender");
            entity.Property(e => e.Height)
                .HasMaxLength(500)
                .HasColumnName("height");
            entity.Property(e => e.Name)
                .HasMaxLength(500)
                .HasColumnName("name");
            entity.Property(e => e.Notes)
                .HasMaxLength(500)
                .HasColumnName("notes");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.Weight)
                .HasMaxLength(500)
                .HasColumnName("weight");

            entity.HasOne(d => d.Animal).WithMany(p => p.Individuals)
                .HasForeignKey(d => d.AnimalId)
                .HasConstraintName("FK__Individua__anima__2BFE89A6");

            entity.HasOne(d => d.Status).WithMany(p => p.Individuals)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Individua__statu__2CF2ADDF");
        });

        modelBuilder.Entity<LeaderAssign>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LeaderAs__3213E83FEECBDB5B");

            entity.ToTable("LeaderAssign");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.FromDate).HasColumnName("from_date");
            entity.Property(e => e.LeaderId).HasColumnName("leader_id");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.ToDate).HasColumnName("to_date");

            entity.HasOne(d => d.Leader).WithMany(p => p.LeaderAssigns)
                .HasForeignKey(d => d.LeaderId)
                .HasConstraintName("FK__LeaderAss__leade__2DE6D218");

            entity.HasOne(d => d.Status).WithMany(p => p.LeaderAssigns)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__LeaderAss__statu__2EDAF651");

            entity.HasOne(d => d.Team).WithMany(p => p.LeaderAssigns)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__LeaderAss__team___2FCF1A8A");
        });

        modelBuilder.Entity<MemberAssign>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MemberAs__3213E83F379DC080");

            entity.ToTable("MemberAssign");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.FromDate).HasColumnName("from_date");
            entity.Property(e => e.MemberId).HasColumnName("member_id");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.ToDate).HasColumnName("to_date");

            entity.HasOne(d => d.Member).WithMany(p => p.MemberAssigns)
                .HasForeignKey(d => d.MemberId)
                .HasConstraintName("FK__MemberAss__membe__30C33EC3");

            entity.HasOne(d => d.Status).WithMany(p => p.MemberAssigns)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__MemberAss__statu__31B762FC");

            entity.HasOne(d => d.Team).WithMany(p => p.MemberAssigns)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK__MemberAss__team___32AB8735");
        });

        modelBuilder.Entity<News>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__News__3213E83F0FDA1858");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccountId).HasColumnName("account_id");
            entity.Property(e => e.Content)
                .HasMaxLength(500)
                .HasColumnName("content");
            entity.Property(e => e.Date)
                .HasColumnType("datetime")
                .HasColumnName("date");
            entity.Property(e => e.Headline)
                .HasMaxLength(500)
                .HasColumnName("headline");
            entity.Property(e => e.StatusId).HasColumnName("status_id");

            entity.HasOne(d => d.Account).WithMany(p => p.News)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__News__account_id__339FAB6E");

            entity.HasOne(d => d.Status).WithMany(p => p.News)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__News__status_id__3493CFA7");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Notifica__3213E83FBD32D309");

            entity.ToTable("Notification");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccountId).HasColumnName("account_id");
            entity.Property(e => e.Content)
                .HasMaxLength(500)
                .HasColumnName("content");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.StatusId).HasColumnName("status_id");

            entity.HasOne(d => d.Account).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__Notificat__accou__3587F3E0");

            entity.HasOne(d => d.Status).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Notificat__statu__367C1819");
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Report__3213E83F24533F0C");

            entity.ToTable("Report");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Content)
                .HasMaxLength(500)
                .HasColumnName("content");
            entity.Property(e => e.Date)
                .HasColumnType("datetime")
                .HasColumnName("date");
            entity.Property(e => e.ReceiverId).HasColumnName("receiver_id");
            entity.Property(e => e.SenderId).HasColumnName("sender_id");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.Title)
                .HasMaxLength(500)
                .HasColumnName("title");

            entity.HasOne(d => d.Receiver).WithMany(p => p.ReportReceivers)
                .HasForeignKey(d => d.ReceiverId)
                .HasConstraintName("FK__Report__receiver__37703C52");

            entity.HasOne(d => d.Sender).WithMany(p => p.ReportSenders)
                .HasForeignKey(d => d.SenderId)
                .HasConstraintName("FK__Report__sender_i__3864608B");

            entity.HasOne(d => d.Status).WithMany(p => p.Reports)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Report__status_i__395884C4");
        });

        modelBuilder.Entity<ReportAttachment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReportAt__3213E83F92A602C7");

            entity.ToTable("ReportAttachment");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.FileUrl).HasColumnName("file_url");
            entity.Property(e => e.ReportId).HasColumnName("report_id");
            entity.Property(e => e.StatusId).HasColumnName("status_id");

            entity.HasOne(d => d.Report).WithMany(p => p.ReportAttachments)
                .HasForeignKey(d => d.ReportId)
                .HasConstraintName("FK__ReportAtt__repor__3A4CA8FD");

            entity.HasOne(d => d.Status).WithMany(p => p.ReportAttachments)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__ReportAtt__statu__3B40CD36");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Role__3213E83F2F22AF52");

            entity.ToTable("Role");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.MaxAbsencePerMonth).HasColumnName("max_absence_per_month");
            entity.Property(e => e.RoleName)
                .HasMaxLength(500)
                .HasColumnName("role_name");
        });

        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Schedule__3213E83F342FE1D8");

            entity.ToTable("Schedule");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccountId).HasColumnName("account_id");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.Note)
                .HasMaxLength(500)
                .HasColumnName("note");
            entity.Property(e => e.StatusId).HasColumnName("status_id");

            entity.HasOne(d => d.Account).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__Schedule__accoun__3C34F16F");

            entity.HasOne(d => d.Status).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Schedule__status__3D2915A8");
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Status__3213E83F2907EA77");

            entity.ToTable("Status");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .HasMaxLength(500)
                .HasColumnName("name");
        });

        modelBuilder.Entity<StatusCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StatusCa__3213E83F1E521141");

            entity.ToTable("StatusCategory");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.StatusId).HasColumnName("status_id");

            entity.HasOne(d => d.Category).WithMany(p => p.StatusCategories)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK__StatusCat__categ__3E1D39E1");

            entity.HasOne(d => d.Status).WithMany(p => p.StatusCategories)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__StatusCat__statu__3F115E1A");
        });

        modelBuilder.Entity<Task>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Task__3213E83F4CE14D48");

            entity.ToTable("Task");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.Note)
                .HasMaxLength(500)
                .HasColumnName("note");
            entity.Property(e => e.Priority)
                .HasMaxLength(500)
                .HasColumnName("priority");
            entity.Property(e => e.ScheduleId).HasColumnName("schedule_id");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.TaskName)
                .HasMaxLength(500)
                .HasColumnName("task_name");
            entity.Property(e => e.TaskTypeId).HasColumnName("task_type_id");
            entity.Property(e => e.TimeEnd).HasColumnName("time_end");
            entity.Property(e => e.TimeStart).HasColumnName("time_start");

            entity.HasOne(d => d.Schedule).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.ScheduleId)
                .HasConstraintName("FK__Task__schedule_i__40058253");

            entity.HasOne(d => d.Status).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Task__status_id__40F9A68C");

            entity.HasOne(d => d.TaskType).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.TaskTypeId)
                .HasConstraintName("FK__Task__task_type___41EDCAC5");
        });

        modelBuilder.Entity<TaskEstimate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TaskEsti__3213E83F329271FF");

            entity.ToTable("TaskEstimate");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnimalTypeId).HasColumnName("animal_type_id");
            entity.Property(e => e.ImplementationProcess)
                .HasMaxLength(500)
                .HasColumnName("implementation_process");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.TaskTypeId).HasColumnName("task_type_id");
            entity.Property(e => e.TimeEstimate)
                .HasMaxLength(500)
                .HasColumnName("time_estimate");

            entity.HasOne(d => d.AnimalType).WithMany(p => p.TaskEstimates)
                .HasForeignKey(d => d.AnimalTypeId)
                .HasConstraintName("FK__TaskEstim__anima__42E1EEFE");

            entity.HasOne(d => d.Status).WithMany(p => p.TaskEstimates)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__TaskEstim__statu__43D61337");

            entity.HasOne(d => d.TaskType).WithMany(p => p.TaskEstimates)
                .HasForeignKey(d => d.TaskTypeId)
                .HasConstraintName("FK__TaskEstim__task___44CA3770");
        });

        modelBuilder.Entity<TaskType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TaskType__3213E83F306CC508");

            entity.ToTable("TaskType");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .HasMaxLength(500)
                .HasColumnName("name");
            entity.Property(e => e.StatusId).HasColumnName("status_id");

            entity.HasOne(d => d.Status).WithMany(p => p.TaskTypes)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__TaskType__status__45BE5BA9");
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Team__3213E83FD4D0A0E3");

            entity.ToTable("Team");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CurrentQuantity).HasColumnName("current_quantity");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.MaxQuantity).HasColumnName("max_quantity");
            entity.Property(e => e.Name)
                .HasMaxLength(500)
                .HasColumnName("name");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.ZooAreaId).HasColumnName("zoo_area_id");

            entity.HasOne(d => d.Status).WithMany(p => p.Teams)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Team__status_id__46B27FE2");

            entity.HasOne(d => d.ZooArea).WithMany(p => p.Teams)
                .HasForeignKey(d => d.ZooAreaId)
                .HasConstraintName("FK__Team__zoo_area_i__47A6A41B");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__User__3213E83FE399A3A1");

            entity.ToTable("User");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccountId).HasColumnName("account_id");
            entity.Property(e => e.Address)
                .HasMaxLength(500)
                .HasColumnName("address");
            entity.Property(e => e.AvartarUrl)
                .HasMaxLength(500)
                .HasColumnName("avartar_url");
            entity.Property(e => e.Email)
                .HasMaxLength(500)
                .HasColumnName("email");
            entity.Property(e => e.Experience)
                .HasMaxLength(20)
                .HasColumnName("experience");
            entity.Property(e => e.Gender)
                .HasMaxLength(20)
                .HasColumnName("gender");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .HasColumnName("phoneNumber");

            entity.HasOne(d => d.Account).WithMany(p => p.Users)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__User__account_id__489AC854");
        });

        modelBuilder.Entity<ZooArea>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ZooArea__3213E83F82432DA2");

            entity.ToTable("ZooArea");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnimalOrder)
                .HasMaxLength(500)
                .HasColumnName("animal_order");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.Location)
                .HasMaxLength(500)
                .HasColumnName("location");
            entity.Property(e => e.Name)
                .HasMaxLength(500)
                .HasColumnName("name");
            entity.Property(e => e.Size)
                .HasMaxLength(500)
                .HasColumnName("size");
            entity.Property(e => e.StatusId).HasColumnName("status_id");

            entity.HasOne(d => d.Status).WithMany(p => p.ZooAreas)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__ZooArea__status___498EEC8D");
        });

        modelBuilder.Entity<ZooAreaImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ZooAreaI__3213E83F8622F496");

            entity.ToTable("ZooAreaImage");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.UrlImage).HasColumnName("url_image");
            entity.Property(e => e.ZooAreaId).HasColumnName("zoo_area_id");

            entity.HasOne(d => d.ZooArea).WithMany(p => p.ZooAreaImages)
                .HasForeignKey(d => d.ZooAreaId)
                .HasConstraintName("FK__ZooAreaIm__zoo_a__4A8310C6");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}