// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Account
{
    public int Id { get; set; }

    public int? RoleId { get; set; }

    public string AccountName { get; set; }

    public string Password { get; set; }

    public string Status { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public DateOnly? UpdatedDate { get; set; }

    public virtual ICollection<AbsentTime> AbsentTimes { get; set; } = new List<AbsentTime>();

    public virtual ICollection<AnimalUpdateHistory> AnimalUpdateHistories { get; set; } = new List<AnimalUpdateHistory>();

    public virtual ICollection<Application> ApplicationRecievers { get; set; } = new List<Application>();

    public virtual ICollection<Application> ApplicationSenders { get; set; } = new List<Application>();

    public virtual ICollection<CageUpdateHistory> CageUpdateHistories { get; set; } = new List<CageUpdateHistory>();

    public virtual ICollection<LeaderAssign> LeaderAssigns { get; set; } = new List<LeaderAssign>();

    public virtual ICollection<MemberAssign> MemberAssigns { get; set; } = new List<MemberAssign>();

    public virtual ICollection<News> News { get; set; } = new List<News>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<Report> ReportReceivers { get; set; } = new List<Report>();

    public virtual ICollection<Report> ReportSenders { get; set; } = new List<Report>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}