// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Role
{
    public int Id { get; set; }

    public string RoleName { get; set; }

    public int? MaxAbsencePerMonth { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();
}