// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class AbsentTime
{
    public int Id { get; set; }

    public int? AccountId { get; set; }

    public int? Reason { get; set; }

    public DateOnly? FromDate { get; set; }

    public DateOnly? ToDate { get; set; }

    public int? StatusId { get; set; }

    public virtual Account Account { get; set; }

    public virtual Status Status { get; set; }
}