// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Animal
{
    public int Id { get; set; }

    public int? AnimalTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateOnly? ArrivalDate { get; set; }

    public string Classify { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<AnimalCage> AnimalCages { get; set; } = new List<AnimalCage>();

    public virtual ICollection<AnimalImage> AnimalImages { get; set; } = new List<AnimalImage>();

    public virtual ICollection<AnimalIncidentHistory> AnimalIncidentHistories { get; set; } = new List<AnimalIncidentHistory>();

    public virtual AnimalType AnimalType { get; set; }

    public virtual ICollection<AnimalUpdateHistory> AnimalUpdateHistories { get; set; } = new List<AnimalUpdateHistory>();

    public virtual ICollection<Flock> Flocks { get; set; } = new List<Flock>();

    public virtual ICollection<Individual> Individuals { get; set; } = new List<Individual>();
}