// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class AnimalImage
{
    public int Id { get; set; }

    public int? AnimalId { get; set; }

    public string UrlImage { get; set; }

    public virtual Animal Animal { get; set; }
}