// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class AnimalType
{
    public int Id { get; set; }

    public string ScientificName { get; set; }

    public string VietnameseName { get; set; }

    public string EnglishName { get; set; }

    public string Family { get; set; }

    public string WeightRange { get; set; }

    public string Characteristics { get; set; }

    public string Distribution { get; set; }

    public string Habitat { get; set; }

    public string Diet { get; set; }

    public string Reproduction { get; set; }

    public string EatFrequency { get; set; }

    public string ConservationStatus { get; set; }

    public string UrlImage { get; set; }

    public virtual ICollection<Animal> Animals { get; set; } = new List<Animal>();

    public virtual ICollection<IncompatibleAnimalType> IncompatibleAnimalTypeAnimalTypeId1Navigations { get; set; } = new List<IncompatibleAnimalType>();

    public virtual ICollection<IncompatibleAnimalType> IncompatibleAnimalTypeAnimalTypeId2Navigations { get; set; } = new List<IncompatibleAnimalType>();

    public virtual ICollection<TaskEstimate> TaskEstimates { get; set; } = new List<TaskEstimate>();
}