// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Application
{
    public int Id { get; set; }

    public int? SenderId { get; set; }

    public int? RecieverId { get; set; }

    public int? ApplicationTypeId { get; set; }

    public string Title { get; set; }

    public string Details { get; set; }

    public string Reply { get; set; }

    public DateTime? Date { get; set; }

    public string Status { get; set; }

    public virtual ApplicationType ApplicationType { get; set; }

    public virtual Account Reciever { get; set; }

    public virtual Account Sender { get; set; }
}