// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Cage
{
    public int Id { get; set; }

    public int? ZooAreaId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Classify { get; set; }

    public int? CurrentQuantity { get; set; }

    public int? MaxQuantity { get; set; }

    public string Size { get; set; }

    public string UrlImage { get; set; }

    public DateOnly? DateCreate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<AnimalCage> AnimalCages { get; set; } = new List<AnimalCage>();

    public virtual ICollection<CageUpdateHistory> CageUpdateHistories { get; set; } = new List<CageUpdateHistory>();

    public virtual ZooArea ZooArea { get; set; }
}