// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class CageUpdateHistory
{
    public int Id { get; set; }

    public int? CageId { get; set; }

    public int? AccountId { get; set; }

    public string Detail { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public virtual Account Account { get; set; }

    public virtual Cage Cage { get; set; }
}