// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class CleaningTask
{
    public int Id { get; set; }

    public int? CleaningOptionId { get; set; }

    public int? AnimalAssignId { get; set; }

    public virtual AnimalAssign AnimalAssign { get; set; }

    public virtual CleaningOption CleaningOption { get; set; }
}