// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class CleaningOption
{
    public int Id { get; set; }

    public int? AnimalTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual AnimalType AnimalType { get; set; }

    public virtual ICollection<CleaningProcess> CleaningProcesses { get; set; } = new List<CleaningProcess>();

    public virtual ICollection<CleaningTask> CleaningTasks { get; set; } = new List<CleaningTask>();
}