// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class CleaningProcess
{
    public int Id { get; set; }

    public int? CleaningOptionId { get; set; }

    public int? StepNumber { get; set; }

    public string Content { get; set; }

    public string Estimatetime { get; set; }

    public virtual CleaningOption CleaningOption { get; set; }

    public virtual ICollection<UrlProcess> UrlProcesses { get; set; } = new List<UrlProcess>();
}