// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Flock
{
    public int Id { get; set; }

    public int? AnimalId { get; set; }

    public int? Quantity { get; set; }

    public string Notes { get; set; }

    public int? StatusId { get; set; }

    public virtual Animal Animal { get; set; }

    public virtual Status Status { get; set; }
}