// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Food
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Decription { get; set; }

    public double? CaloPerGram { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<MealFood> MealFoods { get; set; } = new List<MealFood>();
}