// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class IncidentHistory
{
    public int Id { get; set; }

    public int? AnimalId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ControlMeasures { get; set; }

    public DateOnly? DateStart { get; set; }

    public DateOnly? DateEnd { get; set; }

    public string Status { get; set; }

    public virtual Animal Animal { get; set; }
}