// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class MealDay
{
    public int Id { get; set; }

    public int? AnimalTypeId { get; set; }

    public string Name { get; set; }

    public double? TotalCalo { get; set; }

    public DateTime? PeriodOfTime { get; set; }

    public TimeOnly? TimeStartInDay { get; set; }

    public TimeOnly? TimeEndInDay { get; set; }

    public string Status { get; set; }

    public virtual AnimalType AnimalType { get; set; }

    public virtual ICollection<MealFood> MealFoods { get; set; } = new List<MealFood>();

    public virtual ICollection<TaskMeal> TaskMeals { get; set; } = new List<TaskMeal>();
}