// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class MealFood
{
    public int Id { get; set; }

    public int? MealDayId { get; set; }

    public int? FoodId { get; set; }

    public double? Quantitative { get; set; }

    public virtual Food Food { get; set; }

    public virtual MealDay MealDay { get; set; }
}