// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class ReportAttachment
{
    public int Id { get; set; }

    public int? ReportId { get; set; }

    public string FileUrl { get; set; }

    public int? StatusId { get; set; }

    public virtual Report Report { get; set; }

    public virtual Status Status { get; set; }
}