// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class Status
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<AbsentTime> AbsentTimes { get; set; } = new List<AbsentTime>();

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();

    public virtual ICollection<AnimalAssign> AnimalAssigns { get; set; } = new List<AnimalAssign>();

    public virtual ICollection<AnimalCage> AnimalCages { get; set; } = new List<AnimalCage>();

    public virtual ICollection<AnimalIncidentHistory> AnimalIncidentHistories { get; set; } = new List<AnimalIncidentHistory>();

    public virtual ICollection<Animal> Animals { get; set; } = new List<Animal>();

    public virtual ICollection<ApplicationType> ApplicationTypes { get; set; } = new List<ApplicationType>();

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    public virtual ICollection<CageUpdateHistory> CageUpdateHistories { get; set; } = new List<CageUpdateHistory>();

    public virtual ICollection<Cage> Cages { get; set; } = new List<Cage>();

    public virtual ICollection<Evaluation> Evaluations { get; set; } = new List<Evaluation>();

    public virtual ICollection<Flock> Flocks { get; set; } = new List<Flock>();

    public virtual ICollection<IncompatibleAnimalType> IncompatibleAnimalTypes { get; set; } = new List<IncompatibleAnimalType>();

    public virtual ICollection<Individual> Individuals { get; set; } = new List<Individual>();

    public virtual ICollection<LeaderAssign> LeaderAssigns { get; set; } = new List<LeaderAssign>();

    public virtual ICollection<MemberAssign> MemberAssigns { get; set; } = new List<MemberAssign>();

    public virtual ICollection<News> News { get; set; } = new List<News>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<ReportAttachment> ReportAttachments { get; set; } = new List<ReportAttachment>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    public virtual ICollection<StatusCategory> StatusCategories { get; set; } = new List<StatusCategory>();

    public virtual ICollection<TaskEstimate> TaskEstimates { get; set; } = new List<TaskEstimate>();

    public virtual ICollection<TaskType> TaskTypes { get; set; } = new List<TaskType>();

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();

    public virtual ICollection<ZooArea> ZooAreas { get; set; } = new List<ZooArea>();
}