// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class TaskType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<TaskEstimate> TaskEstimates { get; set; } = new List<TaskEstimate>();

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}