// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class TaskHealth
{
    public int Id { get; set; }

    public int? AnimalAssignId { get; set; }

    public string AnimalCondition { get; set; }

    public string SeverityLevel { get; set; }

    public string DetailInformation { get; set; }

    public virtual AnimalAssign AnimalAssign { get; set; }
}