// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class TaskMeal
{
    public int Id { get; set; }

    public int? MealDayId { get; set; }

    public int? AnimalAssignId { get; set; }

    public double? Percent { get; set; }

    public virtual AnimalAssign AnimalAssign { get; set; }

    public virtual MealDay MealDay { get; set; }
}