// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class UrlProcess
{
    public int Id { get; set; }

    public int? CleaningProcessId { get; set; }

    public string Url { get; set; }

    public virtual CleaningProcess CleaningProcess { get; set; }
}