// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class User
{
    public int Id { get; set; }

    public int? AccountId { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public string Experience { get; set; }

    public string Gender { get; set; }

    public string AvartarUrl { get; set; }

    public virtual Account Account { get; set; }
}