// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class ZooAreaImage
{
    public int Id { get; set; }

    public int? ZooAreaId { get; set; }

    public string UrlImage { get; set; }

    public string Status { get; set; }

    public virtual ZooArea ZooArea { get; set; }
}