// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Models;

public partial class ZooArea
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string AnimalOrder { get; set; }

    public string Location { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Cage> Cages { get; set; } = new List<Cage>();

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();

    public virtual ICollection<ZooAreaImage> ZooAreaImages { get; set; } = new List<ZooAreaImage>();
}